### ISSUE TITLE
Incommpatible with Godot 3.1

### ISSUE THREAD

**Issue by slbdotdev** [Zylann/godot_opensimplex#7]
When trying to use this library in Gdot 3.1, running the project fails with the new parser error:
```
Parser Error: Class 'OsnNoise' shadows a native class.
```

**Comment by Zireael07** [comment]
3.1 from master, 3.1. alpha?

**Comment by Zylann** [comment]
I know this module is going to be merged to Godot 3.1 master (maybe?), so you could also just get this PR instead: https://github.com/godotengine/godot/pull/21569

Otherwise, I have no idea what's going on because `OsnNoise` is fairly descriptive, the module should be compatible. I'd be curious to know which existing class has the same name...
Is it registered once?

**Comment by JFonS** [comment]
My PR is not merged to the master branch yet, so this shouldn't be the cause...

**Comment by slbdotdev** [comment]
I'm not going to worry about this issue if this functionality will be in the engine natively soon.
